# Setup env
FROM node:10-buster-slim
RUN mkdir -p /app
WORKDIR /app
RUN apt update
RUN apt install -y ssh
# For deasync@0.1.14
RUN apt install -y python build-essential
RUN curl -L https://github.com/tsl0922/ttyd/releases/download/1.5.2/ttyd_linux.x86_64 >ttyd-amd64
RUN curl -L https://github.com/tsl0922/ttyd/releases/download/1.5.2/ttyd_linux.aarch64 >ttyd-arm64
RUN chmod +x ttyd-amd64
RUN chmod +x ttyd-arm64

# Setup app
COPY package.json .
COPY package-lock.json .
RUN npm install

# Add app
COPY src src

# Run app
CMD (./ttyd-amd64 --version && (mv ttyd-amd64 /usr/local/bin/ttyd || rm ttyd-amd64)) || mv ttyd-arm64 /usr/local/bin/ttyd; npm run dev